name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  dio: ^5.8.0+1
  lottie: ^3.2.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  objectbox: ^4.0.3
  objectbox_sync_flutter_libs: ^4.0.3
  build_runner: ^2.4.13
  objectbox_generator: ^4.0.3
  equatable: ^2.0.7
  geolocator: ^13.0.2
  get_it: ^8.0.3
  intl: ^0.20.2
  dotted_border: ^2.1.0
  country_code_picker: ^3.2.0
  auto_route: ^9.3.0+1
  connectivity_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/lottie/